export type Styles = {
  "button-primary": string;
  "button-primary__icon": string;
  "button-primary__icon_left": string;
  "button-primary__icon_right": string;
  "button-primary_invert": string;
  "button-primary_large": string;
  "button-primary_medium": string;
  footer: string;
  footer__copyright: string;
  "footer__copyright--social": string;
  "footer__copyright--social-aufacicenta-icon": string;
  "footer__copyright--social-icon": string;
  "footer__copyright--social-item": string;
  "footer__copyright--social-text": string;
  "footer__cta-banner": string;
  "footer__cta-banner--cta": string;
  "footer__cta-banner--description": string;
  "footer__cta-banner--icon": string;
  "footer__cta-banner--link": string;
  "footer__cta-banner--welcome": string;
  "footer__powered-by": string;
  "wallet-selector-navbar": string;
  "wallet-selector-navbar__account-widget": string;
  "wallet-selector-navbar__center": string;
  "wallet-selector-navbar__center--item": string;
  "wallet-selector-navbar__center--item-dropdown": string;
  "wallet-selector-navbar__dropdown": string;
  "wallet-selector-navbar__dropdown--item": string;
  "wallet-selector-navbar__dropdown--item-icon": string;
  "wallet-selector-navbar__dropdown--item-text": string;
  "wallet-selector-navbar__language-selector": string;
  "wallet-selector-navbar__logo": string;
  "wallet-selector-navbar__logo-desktop": string;
  "wallet-selector-navbar__logo-mobile": string;
  "wallet-selector-navbar__right": string;
  "wallet-selector-navbar__right--cta": string;
  "wallet-selector-navbar__right--item": string;
  "z-depth-0": string;
  "z-depth-1": string;
  "z-depth-1-half": string;
  "z-depth-2": string;
  "z-depth-3": string;
  "z-depth-4": string;
  "z-depth-5": string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
